Repository coala/coala, pull requests merged in 2018-07, with the labels that each got.

#5586 PowerShell: Create language file for PowerShell
  coalib/bearlib/languages/definitions/PowerShell.py
Labels: size/XS

#5588 Newcomers_Guide.rst: Add GitLab newcomers group
  docs/Developers/Newcomers_Guide.rst
Labels: difficulty/newcomer, importance/medium, size/XS

#5502 Debug_Bears.rst: Add Debug bears docs
  docs/Developers/Debug_Bears.rst
  docs/index.rst
Labels: area/bears, difficulty/medium, importance/low, size/S, status/ci-approved, type/feature

#5595 languages: Allow more than one comment delimiter
  coalib/bearlib/languages/Language.py
  coalib/bearlib/languages/LanguageDefinition.py
  coalib/bearlib/languages/definitions/C.py
  coalib/bearlib/languages/definitions/CPP.py
  coalib/bearlib/languages/definitions/CSharp.py
  coalib/bearlib/languages/definitions/Fortran.py
  coalib/bearlib/languages/definitions/Golang.py
  coalib/bearlib/languages/definitions/Java.py
  coalib/bearlib/languages/definitions/JavaScript.py
  coalib/bearlib/languages/definitions/Matlab.py
  coalib/bearlib/languages/definitions/PHP.py
  coalib/bearlib/languages/definitions/PowerShell.py
  coalib/bearlib/languages/definitions/Python.py
  coalib/bearlib/languages/definitions/Shell.py
  coalib/bearlib/languages/definitions/TypeScript.py
  coalib/bearlib/languages/definitions/Vala.py
  coalib/bearlib/languages/definitions/__init__.py
  coalib/bearlib/languages/definitions/m4.py
  coalib/results/result_actions/IgnoreResultAction.py
Labels: area/documentation, size/S

#5601 Linter: Add option to remove 0 number
  coalib/bearlib/abstractions/Linter.py
  tests/bearlib/abstractions/LinterTest.py
Labels: size/XS, type/bug

#5562 Add memoization to FileFactory
  coalib/io/FileFactory.py
  coalib/io/memoized_property.py
  tests/io/FileFactoryTest.py
Labels: size/XS

#5612 Useful_Links.rst: Change Basic rST link
  docs/Developers/Useful_Links.rst
Labels: area/documentation, difficulty/newcomer, size/XS

#5581 VisualBasic: Create language file for Visual Basic
  coalib/bearlib/languages/definitions/VisualBasic.py
Labels: area/languages, difficulty/low, importance/low, size/XS

#5630 BearTest: Replace httpstat with Google teapot
  tests/bears/BearTest.py
  tests/core/BearTest.py
Labels: area/CI, area/tests, size/XS, status/ci-approved, type/bug

#5629 aspects: Rename class `docs` to follow CapWords
  coalib/bearlib/aspects/Formatting.py
  coalib/bearlib/aspects/Metadata.py
  coalib/bearlib/aspects/Redundancy.py
  coalib/bearlib/aspects/Security.py
  coalib/bearlib/aspects/Smell.py
  coalib/bearlib/aspects/Spelling.py
  coalib/bearlib/aspects/meta.py
  coalib/bearlib/aspects/root.py
  coalib/results/Result.py
  tests/bearlib/aspects/ClassTest.py
  tests/bearlib/aspects/conftest.py
  tests/results/result_actions/PrintAspectActionTest.py
Labels: difficulty/low, size/S, type/codestyle

#5616 .travis.yml: Use bears master
  .travis.yml
Labels: size/XS

#5624 .moban.yaml: Add cached_property
  .moban.yaml
Labels: size/XS

#5583 requirements.txt: Remove testfixtures
  .moban.dt/core-test-requirements.txt.jj2
  .moban.yaml
  requirements.txt
  test-requirements.txt
Labels: difficulty/low, importance/critical, size/XS

#5634 check_unsupported.sh: Use template
  .misc/check_unsupported.sh
Labels: size/XS

#4088 Add pytest-travis-fold
  test-requirements.txt
Labels: size/XS, status/stale

#5352 ConsoleInteraction.py: Improve error message
  coalib/output/ConsoleInteraction.py
Labels: area/CLI, difficulty/low, size/XS

#5458 CliParsing.py: Throw error for conflicting arguments
  coalib/parsing/CliParsing.py
  tests/parsing/CliParsingTest.py
Labels: area/CLI, difficulty/low, size/XS, type/bug

#5641 appveyor.yml: Sync moban
  .misc/appveyor.yml
  setup.py
Labels: platform/windows, size/XS, type/bug

#5622 requirements.txt: Use coala-utils master
  .moban.yaml
  requirements.txt
Labels: size/XS

#5298 coala_modes.py: Warn for log_printer param
  coalib/coala_modes.py
Labels: area/CLI, difficulty/low, process/pending review, size/XS

#5639 Update Writing_Tests.rst: Remove unwanted quotes
  docs/Developers/Writing_Tests.rst
Labels: area/documentation, difficulty/newcomer, size/XS

#5648 Smell.py: Fix docstring typo
  coalib/bearlib/aspects/Smell.py
Labels: area/documentation, difficulty/newcomer, size/XS

#5660 test-requirements.txt: Moban Sync
  test-requirements.txt
Labels: size/XS

#5651 TestUtilities: Add sorted test bear list
  tests/TestUtilities.py
  tests/coalaJSONTest.py
  tests/collecting/CollectorsTest.py
  tests/settings/ConfigurationGatheringTest.py
Labels: size/XS, status/blocked

#5672 coalaJSONTest: Remove unnecessary second patch
  tests/coalaJSONTest.py
  tests/coalaTest.py
Labels: area/CLI, area/tests, difficulty/low, importance/low, process/approved, size/XS

#5673 Constants: Move USER_DATA_DIR to CachingUtilities
  coalib/misc/CachingUtilities.py
  coalib/misc/Constants.py
Labels: area/CLI, area/tests, difficulty/low, importance/low, size/XS, type/bug

#5610 Bears.py: Add Debugger Setting toolset
  coalib/bears/Bear.py
  tests/bears/BearTest.py
  tests/bears/DebugBearsTest.py
Labels: size/S

#5620 Debug_bears.rst: Add Debugger Settings docs
  docs/Developers/Debug_Bears.rst
Labels: size/XS, status/blocked, status/ci-approved

#5669 setup.cfg: Use template
  .moban.dt/core-setup.cfg.jj2
  .moban.yaml
  setup.cfg
  tests/conftest.py
Labels: size/S

#5514 Meta-review.rst: Add meta-review docs
  docs/Developers/Meta-review.rst
  docs/index.rst
Labels: area/documentation, difficulty/medium, process/pending review, size/S

#5653 CachingUtilities.py: Remove unused local variable
  coalib/misc/CachingUtilities.py
Labels: difficulty/newcomer, size/XS, type/codestyle

#5681 .coafile: Modify circleci config file location
  .coafile
Labels: area/CI, difficulty/newcomer, importance/medium, size/XS, type/codestyle
