Repository coala/coala, pull requests merged in 2018-09, with the labels that each got.

#5742 Collectors.py: Discard trailing ** in ignore glob
  coalib/collecting/Collectors.py
  tests/collecting/CollectorsTest.py
Labels: difficulty/low, importance/high, process/pending review, size/XS

#5729 Newcomers_Guide.rst: Mention "Adding CI"
  docs/Developers/Newcomers_Guide.rst
Labels: difficulty/newcomer, importance/low, process/pending review, size/XS

#5723 LocalBearTestHelper: Decommission timeout
  coalib/testing/LocalBearTestHelper.py
Labels: area/CI, area/tests, process/pending review, size/XS, type/bug

#5744 .coafile: Remove trailing globstars
  .coafile
Labels: process/pending review, size/XS

#5482 .ci/appveyor.yml: Add Python 3.6 jobs
  .misc/appveyor.yml
  .moban.yaml
Labels: process/pending review, size/XS

#5705 .travis.yml: Disable install on unsupported
  .travis.yml
Labels: area/CI, process/pending review, size/XS

#5758 setup.cfg: Raise Appveyor timeout limit
  setup.cfg
Labels: area/CI, size/XS, type/bug

#5748 SCSS.py: Add SCSS.py file
  coalib/bearlib/languages/definitions/SCSS.py
  tests/TestUtilities.py
Labels: area/languages, difficulty/low, importance/medium, size/XS

#5752 Writing_Good_Commits.rst: Fix Mistake
  docs/Developers/Writing_Good_Commits.rst
Labels: area/aspects, area/documentation, difficulty/newcomer, size/XS
