Repository coala/coala, pull requests merged in 2018-02, with the labels that each got.

#5053 Ignore additional parameters if a section disabled
  coalib/settings/ConfigurationGathering.py
  coalib/settings/SectionFilling.py
  tests/coalaCITest.py
  tests/settings/SectionFillingTest.py
Labels: difficulty/medium, importance/critical, size/XS, type/bug

#4310 LocalBearTestHelper: Add ``assertObjectsEqual``
  coalib/testing/LocalBearTestHelper.py
  tests/testing/LocalBearTestHelperTest.py
Labels: area/tests, difficulty/medium, review carefully!, size/S, status/blocked, status/stale

#4899 Linter_Bears_Advanced.rst: Explains return `None`
  docs/Developers/Linter_Bears_Advanced.rst
Labels: area/documentation, difficulty/low, importance/high, size/XS, status/stale, type/performance

#4915 from_clang: Report useful error
  coalib/results/Diff.py
  coalib/results/SourceRange.py
  tests/results/DiffTest.py
  tests/results/SourceRangeTest.py
Labels: difficulty/low, size/XS, status/stale

#5110 Newcomers_Guide.rst : Add smart question link
  docs/Developers/Newcomers_Guide.rst
Labels: area/documentation, difficulty/newcomer, size/XS

#5128 package.json: Remove extra spacing
  package.json
Labels: difficulty/newcomer, size/XS

#5140 setup.py: Fix the location of Man Page
  setup.py
Labels: difficulty/medium, importance/medium, size/XS

#5163 .editorconfig: Correct typo
  .editorconfig
Labels: area/documentation, difficulty/newcomer, size/XS

#5145 FilterHelper.py: Move code from Filter.py
  coalib/parsing/FilterHelper.py
  coalib/parsing/filters/CanDetectFilter.py
  coalib/parsing/filters/CanFixFilter.py
  coalib/parsing/filters/Filter.py
  coalib/parsing/filters/LanguageFilter.py
Labels: area/CLI, difficulty/low, size/XS

#5130 LocalBearTestHelper: Add ``check_order`` in doc
  coalib/testing/LocalBearTestHelper.py
Labels: area/documentation, difficulty/low, size/XS

#5151 FunctionMetadata.py: Typo Error
  coalib/settings/FunctionMetadata.py
Labels: difficulty/newcomer, size/XS

#5164 .gitignore: Add names to ignore tag files in vim
  .gitignore
Labels: difficulty/newcomer, size/XS

#5182 Linter_Bears_Advanced.rst: Fix typo
  docs/Developers/Linter_Bears_Advanced.rst
Labels: area/documentation, difficulty/newcomer, size/XS

#5068 Support for section ordering
  coalib/coala_main.py
  tests/coalaCITest.py
Labels: area/CLI, area/core, difficulty/medium, size/XS, type/feature

#4970 core: Make bear dependencies instance bound
  coalib/core/Bear.py
  coalib/core/Core.py
  tests/core/BearTest.py
  tests/core/CoreTest.py
Labels: area/bears, area/core, difficulty/medium, size/S
