Repository coala/coala, pull requests merged in 2018-10, with the labels that each got.

#5774 CPP.py: Remove blank line
  coalib/bearlib/languages/definitions/CPP.py
Labels: difficulty/newcomer, size/XS, type/codestyle

#5761 Writing_Documentation.rst: Modify a command
  docs/Developers/Writing_Documentation.rst
Labels: difficulty/newcomer, process/pending review, size/XS

#5759 Haskell.py: Add Haskell.py file
  coalib/bearlib/languages/definitions/Haskell.py
  tests/TestUtilities.py
Labels: area/languages, difficulty/medium, importance/medium, process/pending review, size/XS

#5793 default.py: Remove erroneous mention of docstrings
  tests/bearlib/languages/documentation/DocumentationCommentTest.py
  tests/bearlib/languages/documentation/documentation_extraction_testdata/default.py
Labels: area/languages, area/tests, difficulty/newcomer, importance/medium, process/pending review, size/XS

#5727 Release notes now published at api docs
  docs/.gitignore
  docs/index.rst
  docs/release_notes.rst
Labels: area/documentation, difficulty/newcomer, process/pending review, size/XS

#5650 docs: Update Newcomers_Guide.rst
  docs/Developers/Newcomers_Guide.rst
Labels: area/documentation, difficulty/newcomer, process/pending review, size/XS

#5789 ConfParserTest.py: Fix typos in comments
  tests/parsing/ConfParserTest.py
Labels: area/documentation, difficulty/newcomer, process/pending review, size/XS

#5803 moban: Moban Sync
  .gitignore
  setup.cfg
  test-requirements.txt
Labels: process/pending review, size/XS

#5783 Git_Basics.rst: Maximum line length of commit body change to 72
  docs/Developers/Git_Basics.rst
Labels: area/documentation, difficulty/newcomer, process/pending review, size/XS

#5741 CachingUtilities.py: Fix description
  coalib/misc/CachingUtilities.py
Labels: difficulty/low, importance/medium, process/pending review, size/XS, type/bug

#5806 SectionFilling: Make targets optional
  coalib/settings/ConfigurationGathering.py
  coalib/settings/SectionFilling.py
  tests/settings/SectionFillingTest.py
Labels: difficulty/low, importance/critical, process/pending review, size/XS

#5804 Addition of Visual Studio Code to the list of known editors
  coalib/results/result_actions/OpenEditorAction.py
Labels: area/documentation, difficulty/newcomer, process/pending review, size/XS

#5436 ConfigurationGathering.py: Change COAFILE_OUTPUT to refer to .coafile
  coalib/settings/ConfigurationGathering.py
  tests/settings/ConfigurationGatheringTest.py
Labels: area/CLI, area/config, difficulty/low, importance/low, process/pending review, size/XS

#5800 Fixing typo in Writing_Native_Bears.rst
  docs/Developers/Writing_Native_Bears.rst
Labels: area/documentation, difficulty/newcomer, process/pending review, size/XS

#5809 Revert "Globbing.py: Return False if globs are..."
  coalib/parsing/Globbing.py
  tests/parsing/GlobbingTest.py
Labels: importance/critical, process/pending review, size/XS, type/bug

#5828 antlr.py: Add g4 file
  coalib/bearlib/languages/__init__.py
  coalib/bearlib/languages/definitions/antlr.py
  tests/TestUtilities.py
Labels: area/aspects, area/documentation, process/pending review, size/XS

#5840 Writing_Good_Commits.rst: Use better examples
  docs/Developers/Writing_Good_Commits.rst
Labels: area/documentation, difficulty/low, process/pending review, size/S

#5833 Add language definition file for D
  coalib/bearlib/languages/__init__.py
  coalib/bearlib/languages/definitions/D.py
  tests/TestUtilities.py
Labels: area/CI, area/languages, difficulty/low, importance/low, process/pending review, size/XS

#5816 Newcomers_Guide.rst: Explain newcomer issues
  docs/Developers/Newcomers_Guide.rst
Labels: process/pending review, size/XS

#5845 coalib/output/ConsoleInteraction.py: Modifies the docstring
  coalib/output/ConsoleInteraction.py
Labels: difficulty/newcomer, process/pending review, size/XS

#5853 Result.py: Add docstring regarding the case that line or column is None
  coalib/results/Result.py
Labels: area/documentation, difficulty/low, importance/medium, process/pending review, size/XS

#5807 Newcomers_Guide.rst: Include 2 new paragraphs
  docs/Developers/Newcomers_Guide.rst
Labels: area/documentation, difficulty/newcomer, process/pending review, size/XS

#5851 TinyBasic.py: Add language definition of TinyBasic
  coalib/bearlib/languages/__init__.py
  coalib/bearlib/languages/definitions/TinyBasic.py
  tests/TestUtilities.py
Labels: area/aspects, area/documentation, area/languages, difficulty/medium, initiatives/gci, process/pending review, size/XS

#5846 Review.rst: Add review confirmation policy to doc
  docs/Developers/Review.rst
Labels: area/documentation, difficulty/newcomer, process/pending review, size/XS

#5811 Setting.py: Add SourcePosition to Setting.origin
  coalib/parsing/ConfParser.py
  coalib/results/SourcePosition.py
  coalib/settings/ConfigurationGathering.py
  coalib/settings/Setting.py
  tests/parsing/ConfParserTest.py
  tests/results/SourcePositionTest.py
  tests/settings/SettingTest.py
Labels: area/CLI, difficulty/medium, importance/medium, process/pending review, size/S, type/bug

#5814 __init__.py: Arrange imports alphabetically
  coalib/bearlib/languages/__init__.py
Labels: difficulty/newcomer, process/pending review, size/XS

#5864 collecting: Fix incorrect trailing '**' warning
  coalib/collecting/Collectors.py
  tests/collecting/CollectorsTest.py
Labels: difficulty/low, importance/high, process/pending review, size/XS, type/bug
