Repository coala/coala, pull requests merged in 2018-06, with the labels that each got.

#5503 .travis.yml: Add separate moban job
  .misc/check_moban.sh
  .moban.yaml
  .travis.yml
Labels: size/XS

#5494 Shell: Use sys.executable in doctest
  coalib/misc/Shell.py
Labels: process/pending review, size/XS

#5483 Testing_Bears.rst: Change check_validity docs
  docs/Developers/Testing_Bears.rst
Labels: area/documentation, difficulty/low, importance/medium, size/XS

#5493 Update TypeScript keywords
  coalib/bearlib/languages/definitions/TypeScript.py
Labels: area/documentation, difficulty/newcomer, size/XS

#5496 BaseTestHelper.py: Add `BaseTestHelper` class
  coalib/testing/BaseTestHelper.py
  tests/testing/BaseTestHelperTest.py
Labels: difficulty/medium, size/XS, status/needs design

#5484 Moban test requirements
  .moban.yaml
  test-requirements.txt
Labels: size/XS

#5461 Formatting: Add description to `preferred_quotation`
  coalib/bearlib/aspects/Formatting.py
Labels: area/aspects, area/documentation, process/pending review, size/XS

#5487 Newcomers.rst: Add a command pytest to the guide
  docs/Developers/Newcomers_Guide.rst
Labels: area/documentation, difficulty/newcomer, process/pending review, size/XS

#5485 Add FileFactory.py
  coalib/io/FileFactory.py
  coalib/io/__init__.py
  tests/io/FileFactoryTest.py
  tests/io/FileFactoryTestFiles/test1.txt
  tests/io/FileFactoryTestFiles/test2.txt
  tests/io/__init__.py
Labels: area/core, difficulty/high, size/S

#5498 Add Directory class
  coalib/io/Directory.py
  tests/io/DirectoryTest.py
  tests/io/DirectoryTestDir/Dir1/test2.txt
  tests/io/DirectoryTestDir/Dir2/test3.txt
  tests/io/DirectoryTestDir/test1.txt
Labels: area/core, difficulty/high, size/S, status/needs design

#5500 .travis.yml: Add man page test
  .ci/check_man.sh
  .circleci/config.yml
  .travis.yml
Labels: area/documentation, area/install, area/tests, difficulty/medium, importance/medium, size/XS

#5507 .gitignore: Use moban template
  .gitignore
  .moban.dt/core-gitignore.jj2
  .moban.yaml
Labels: size/L

#5542 .travis.yml: Add sentinel job
  .travis.yml
Labels: size/XS

#5544 Language: Change `TrumpScript` aliases
  coalib/bearlib/languages/Language.py
Labels: difficulty/low, importance/high, process/pending review, size/XS, type/bug

#5540 TypeScript.py: Change aliases to type tuple
  coalib/bearlib/languages/definitions/TypeScript.py
Labels: difficulty/newcomer, size/XS

#5492 aspects: Create `map_ambiguous_setting_to_aspect`
  coalib/bearlib/aspects/__init__.py
  coalib/bearlib/aspects/decorators.py
  tests/bearlib/aspects/DecoratorsTest.py
Labels: area/aspects, size/S, type/feature

#5548 Add pytest-profiling
  setup.cfg
  test-requirements.txt
Labels: size/XS

#5552 Replace range variable with different name
  coalib/bearlib/abstractions/Linter.py
  coalib/results/Result.py
Labels: difficulty/newcomer, process/pending review, size/XS, type/codestyle

#5553 ResultAction.py: Fix docstring typo
  coalib/results/result_actions/ResultAction.py
Labels: difficulty/newcomer, size/XS

#5557 Development_Setup.rst: Fix Broken Links
  docs/Developers/Development_Setup.rst
Labels: area/documentation, difficulty/newcomer, size/XS, type/bug

#5558 CI: Check man page without altering $MANPATH
  .ci/check_man.sh
  .circleci/config.yml
Labels: area/documentation, area/install, area/tests, difficulty/medium, importance/medium, process/pending review, size/XS

#5576 Tcl: Create basic language file for tcl
  coalib/bearlib/languages/definitions/Tcl.py
Labels: difficulty/low, size/XS

#5577 m4: Create language file for m4
  coalib/bearlib/languages/definitions/m4.py
Labels: difficulty/medium, process/pending review, size/XS

#5511 Add: Debugging Interface
  coalib/bears/Bear.py
  coalib/bears/GlobalBear.py
  coalib/parsing/DefaultArgParser.py
  coalib/processes/Processing.py
  tests/bears/BearTest.py
  tests/bears/DebugBearsTest.py
  tests/processes/ProcessingTest.py
Labels: size/M, status/ci-approved
