Repository coala/coala, pull requests merged in 2018-04, with the labels that each got.

#5322 setup.py: Revert use of invalid classifier
  setup.py
Labels: difficulty/newcomer, importance/high, process/pending review, size/XS, type/bug

#5323 PULL_REQUEST_TEMPLATE.md: Change cobot to corobo
  PULL_REQUEST_TEMPLATE.md
Labels: area/CI, difficulty/newcomer, size/XS

#5284 Development_Setup: Change cd - to cd ..
  docs/Developers/Development_Setup.rst
Labels: area/documentation, difficulty/newcomer, size/XS

#5283 Writing_Linter_Bears.rst: Clean docs
  docs/Developers/Writing_Linter_Bears.rst
Labels: area/documentation, difficulty/newcomer, size/XS

#5200 Review.rst: Update review docs
  docs/Developers/Review.rst
Labels: area/documentation, difficulty/low, size/XS

#5304 Writing_Good_Commits.rst: Add No WIP prefix
  docs/Developers/Writing_Good_Commits.rst
Labels: area/documentation, difficulty/low, importance/low, size/XS

#5293 ConsoleInteraction.py : Fix error message
  coalib/output/ConsoleInteraction.py
Labels: area/CLI, difficulty/newcomer, size/XS

#5294 Matlab.py: Add comment delimiter for Matlab & Octave
  coalib/bearlib/languages/definitions/Matlab.py
Labels: area/actions, size/XS, type/bug

#5221 ShowAppliedPatchesAction.py : Success Message
  coalib/results/result_actions/ShowAppliedPatchesAction.py
Labels: difficulty/low, process/pending review, size/XS, type/bug

#4993 requirements.txt: Upgrade to colorlog 3.1
  requirements.txt
Labels: area/CI, size/XS

#5124 Fixes #3259 - Modified: Writing_Good_Commits.rst
  docs/Developers/Writing_Good_Commits.rst
Labels: area/documentation, area/tests, difficulty/newcomer, size/XS, type/bug

#5258 OpenEditorAction.py: Add notepadqq to known editors
  coalib/results/result_actions/OpenEditorAction.py
Labels: area/actions, difficulty/newcomer, size/XS

#5279 Add markdown language definition
  coalib/bearlib/languages/definitions/Markdown.py
Labels: area/CI, difficulty/medium, importance/medium, size/XS

#5344 setup.py: Remove man pages on Windows
  setup.py
Labels: area/documentation, difficulty/newcomer, platform/windows, size/XS, type/bug

#5234 config.yml: Update CircleCI syntax
  .circleci/config.yml
  .misc/deps.sh
  circle.yml
  tests/misc/ContextManagersTest.py
Labels: area/CI, difficulty/medium, importance/critical, size/S

#5339 .travis.yml : Add python 3.4.3 check
  .travis.yml
Labels: difficulty/low, importance/medium, size/XS, type/bug

#5381 .coafile: Ignore new pycodestyle's checks
  .coafile
Labels: difficulty/low, importance/critical, size/XS, type/codestyle

#5380 .circleci/config.yml: Change cached paths
  .circleci/config.yml
Labels: area/CI, difficulty/low, importance/medium, size/XS, type/bug

#5377 tests/: Fix typos "instantation"
  tests/bearlib/languages/documentation/DocstyleDefinitionTest.py
  tests/results/TextPositionTest.py
  tests/results/TextRangeTest.py
Labels: difficulty/newcomer, size/XS, type/bug

#5105 Development_Setup.rst: Rephrase instructions
  docs/Developers/Development_Setup.rst
Labels: difficulty/medium, importance/medium, size/XS

#5361 coalib/bearlib/languages: import Markdown
  coalib/bearlib/languages/__init__.py
Labels: area/CI, area/documentation, difficulty/newcomer, size/XS

#5349 Linter_Bears_Advanced.rst: Fixed indentation
  docs/Developers/Linter_Bears_Advanced.rst
Labels: area/documentation, difficulty/newcomer, size/XS

#4897 Build setup.py and requirements.txt using moban
  .coafile
  .moban.dt/core-setup.py.jj2
  .moban.yaml
  .travis.yml
  setup.py
  test-requirements.txt
Labels: size/S, status/stale

#5285 ConsoleInteraction: Fix a typo
  coalib/output/ConsoleInteraction.py
Labels: difficulty/newcomer, size/XS

#5138 tests/coalaTest.py: Add test case for ignore flag
  tests/coalaTest.py
Labels: area/tests, difficulty/low, size/XS

#5393 ConsoleInteractionTest: Remove check_logs usage
  tests/output/ConsoleInteractionTest.py
Labels: size/XS

#5347 Linter.py: Support colorised output from linters
  .moban.yaml
  coalib/bearlib/abstractions/Linter.py
  requirements.txt
  tests/bearlib/abstractions/LinterTest.py
Labels: area/lintbears, difficulty/medium, size/XS

#5395 E241 check is being enforced
  .coafile
  tests/testing/LocalBearTestHelperTest.py
Labels: difficulty/newcomer, size/XS, type/bug

#5387 Git_Basics.rst: Incorporate http://ohshitgit.com/
  docs/Developers/Git_Basics.rst
Labels: area/documentation, difficulty/newcomer, size/XS

#5054 ConfigurationGathering.py: Refactor targets list
  coalib/settings/ConfigurationGathering.py
Labels: difficulty/newcomer, size/XS, type/codestyle

#5313 FilterHelperTest.py: Add `FilterHelperTest` class
  tests/parsing/FilterHelperTest.py
Labels: area/tests, difficulty/low, size/XS

#4950 FilterHelper.apply_filter: Add docstring
  coalib/parsing/FilterHelper.py
Labels: area/documentation, difficulty/low, process/pending review, size/XS, status/stale

#5119 Newcomers_Guide: Improves emphasis of material
  docs/Developers/Newcomers_Guide.rst
  docs/_static/custom.css
Labels: area/documentation, difficulty/low, size/XS

#5267 ConsoleInteraction.py: Apply the DoNothingAction
  coalib/output/ConsoleInteraction.py
Labels: area/actions, difficulty/low, size/XS

#5088 Newcomers_Guide.rst: Add reference to GitLab repo
  docs/Developers/Newcomers_Guide.rst
Labels: difficulty/newcomer, process/pending review, size/XS

#5402 ConsoleInteraction.py: Fix coala -B --json
  .circleci/config.yml
  .misc/appveyor.yml
  .travis.yml
  coalib/output/ConsoleInteraction.py
  tests/coalaJSONTest.py
Labels: area/CLI, difficulty/low, process/pending review, size/XS, status/blocked

#5134 Collectors.py: Use bear names without suffix
  coalib/collecting/Collectors.py
  tests/collecting/CollectorsTest.py
  tests/collecting/collectors_test_dir/bears/nameBear.py
Labels: area/CLI, area/bears, area/usability, difficulty/medium, size/XS

#5407 CI: Remove coala -B --json
  .circleci/config.yml
  .misc/appveyor.yml
  .travis.yml
Labels: size/XS

#5405 Review.rst: Add more details for reviewers
  docs/Developers/Review.rst
Labels: size/XS

#5252 Linter_Bears_Advanced.rst: Linter tutorials brush-up
  docs/Developers/Linter_Bears_Advanced.rst
Labels: area/documentation, difficulty/low, process/pending review, size/XS

#5414 Makman2/strip ansi fix
  coalib/bearlib/abstractions/Linter.py
  tests/bearlib/abstractions/LinterTest.py
Labels: area/lintbears, difficulty/low, importance/high, process/pending review, size/XS, type/bug

#5367 TextPosition.py: Raise exception for zero offset
  coalib/bearlib/languages/documentation/DocumentationComment.py
  coalib/bears/Bear.py
  coalib/results/TextPosition.py
  tests/bearlib/abstractions/LinterTest.py
  tests/bearlib/abstractions/linter_test_files/test_linter.py
  tests/bears/BearTest.py
  tests/results/TextPositionTest.py
  tests/results/TextRangeTest.py
Labels: area/CI, area/bears, area/lintbears, difficulty/medium, importance/medium, process/pending review, size/S, type/feature

#5350 linter: Add new parameters to normalize numbers
  coalib/bearlib/abstractions/Linter.py
  docs/Developers/Writing_Linter_Bears.rst
  tests/bearlib/abstractions/LinterTest.py
Labels: area/lintbears, difficulty/low, size/S

#4842 Collectors.py: Add support to ignore directories
  coalib/collecting/Collectors.py
  coalib/misc/IterUtilities.py
  coalib/parsing/Globbing.py
  tests/collecting/CollectorsTest.py
Labels: area/config, difficulty/high, importance/high, review carefully!, size/S, status/stale

#5421 Constants.py, GatheringTest.py: Fix typo
  coalib/misc/Constants.py
  tests/settings/ConfigurationGatheringTest.py
Labels: difficulty/newcomer, size/XS, type/bug

#5262 docs: Adds NextGen-Core docs
  docs/Developers/NextGen_Core.rst
  docs/index.rst
Labels: area/documentation, difficulty/medium, size/M

#4009 DocComment: Parse references to different objects in docstring
  coalib/bearlib/languages/documentation/DocumentationComment.py
  tests/bearlib/languages/documentation/DocumentationCommentTest.py
Labels: process/pending review, size/XS, status/stale

#5427 CollectorsTest.py: Remove unnecessary parameters
  tests/collecting/CollectorsTest.py
Labels: area/tests, difficulty/newcomer, importance/low, size/XS
