Repository coala/coala, pull requests merged in 2018-05, with the labels that each got.

#5428 Jinja2.py: Add support for ignore comments
  coalib/bearlib/languages/__init__.py
  coalib/bearlib/languages/definitions/Jinja2.py
  tests/results/result_actions/IgnoreResultActionTest.py
Labels: area/actions, difficulty/low, size/XS, type/feature

#5443 CachingUtilities.py: Removes unnecessary imports
  coalib/misc/CachingUtilities.py
Labels: difficulty/newcomer, importance/low, size/XS

#5447 Formatting.py: Fixing a typo
  coalib/bearlib/aspects/Formatting.py
Labels: area/aspects, difficulty/newcomer, process/pending review, size/XS

#5448 ConfigurationGatheringTest.py: Save user_coafile before modify
  tests/settings/ConfigurationGatheringTest.py
Labels: area/config, area/tests, difficulty/low, importance/low, size/XS

#5459 setup.py: Sync moban
  setup.py
Labels: size/XS

#5437 FilterTest.py: Import available_filters directly
  tests/parsing/FilterTest.py
Labels: area/tests, difficulty/newcomer, importance/low, process/pending review, size/XS

#5452 Executing_Tests.rst: Mention codecov
  docs/Developers/Executing_Tests.rst
Labels: area/documentation, difficulty/low, importance/low, size/XS

#5450 Writing_Linter_Bears.rst: Fix method definition
  docs/Developers/Writing_Linter_Bears.rst
Labels: area/documentation, process/pending review, size/XS, status/needs info, type/bug

#5467 appveyor.yml: Run pip install as Python module
  .misc/appveyor.yml
Labels: area/CI, size/XS

#5426 Netlify docs
  .moban.yaml
  netlify.toml
  runtime.txt
Labels: size/XS

#5472 Fix invalid escape sequence and remove W605 from ignore list
  .coafile
  coalib/bearlib/aspects/__init__.py
  coalib/bearlib/aspects/meta.py
  coalib/bearlib/languages/definitions/C.py
  coalib/bearlib/languages/definitions/CPP.py
  coalib/bearlib/languages/documentation/DocumentationExtraction.py
  coalib/bearlib/naming_conventions/__init__.py
  tests/bearlib/aspects/CollectionsTest.py
  tests/coalaTest.py
  tests/collecting/CollectorsTest.py
  tests/parsing/LineParserTest.py
Labels: difficulty/low, importance/medium, size/XS, type/bug
