Repository coala/coala, pull requests merged in 2018-03, with the labels that each got.

#5247 requirements.txt: Unpin packaging
  requirements.txt
Labels: area/CI, area/upstream, size/XS, type/bug

#5209 appveyor.yml: Remove everything related to LLVM
  .misc/appveyor.yml
Labels: area/CI, difficulty/low, size/XS

#5229 Writing_Linter_Bears.rst: Fix typo
  docs/Developers/Writing_Linter_Bears.rst
Labels: area/documentation, difficulty/newcomer, size/XS

#5180 Writing_Linter_Bears.rst: Improve quotes style
  docs/Developers/Writing_Linter_Bears.rst
Labels: area/documentation, difficulty/newcomer, size/XS

#5144 coalaCITest.py: Add --bear-dirs test
  tests/coalaCITest.py
Labels: area/CLI, area/tests, difficulty/medium, size/XS

#5253 core: Don't offer implicit dependency results
  coalib/core/Core.py
  tests/core/CoreTest.py
  tests/core/DependencyBearTest.py
Labels: area/core, difficulty/medium, size/S

#5256 Linter.py: Correct docstring
  coalib/bearlib/abstractions/Linter.py
Labels: area/documentation, difficulty/newcomer, size/XS

#5268 .travis.yml: Skip unsupported except on master
  .travis.yml
Labels: difficulty/low, size/XS

#5265 Writing_Documentation.rst: Fix url
  docs/Developers/Writing_Documentation.rst
Labels: area/documentation, difficulty/newcomer, size/XS

#5226 Result.py: Compare diffs
  coalib/results/Result.py
  tests/results/ResultTest.py
Labels: area/tests, difficulty/medium, importance/high, process/pending review, size/XS, type/bug

#5271 Core.py: Removes section from docstring
  coalib/core/Core.py
Labels: area/documentation, difficulty/low, size/XS

#5259 Globbing.py: Return false if globs are absent
  coalib/parsing/Globbing.py
  tests/parsing/GlobbingTest.py
Labels: area/core, difficulty/medium, size/XS

#5272 Related clang stuff removed
  tests/misc/ExceptionsTest.py
  tests/output/ConsoleInteractionTest.py
Labels: area/tests, difficulty/low, importance/low, process/pending review, size/XS

#5102 Development_Setup.rst: Update Documentation generation instructions
  docs/Developers/Development_Setup.rst
Labels: area/documentation, difficulty/newcomer, size/XS, status/stale

#5204 Writing_Good_Commits.rst: Fix typo
  docs/Developers/Writing_Good_Commits.rst
Labels: area/documentation, difficulty/newcomer, importance/high, size/XS, status/stale

#5125 Required changes made
  RELEASE_NOTES.rst
Labels: area/documentation, difficulty/newcomer, size/XS
