Repository coala/coala, pull requests merged in 2018-08, with the labels that each got.

#5677 Bear: Remove debugger from init
  coalib/bears/Bear.py
  coalib/bears/GlobalBear.py
  coalib/processes/Processing.py
  tests/bears/BearTest.py
  tests/processes/ProcessingTest.py
Labels: size/S, status/ci-approved

#5638 LocalBearTestHelper: Modify for `aspects` testing
  coalib/testing/LocalBearTestHelper.py
  tests/testing/LocalBearTestHelperTest.py
Labels: area/aspects, area/documentation, process/needs rebase, size/XS

#5599 Add: Profiling Interface
  coalib/bears/Bear.py
  coalib/parsing/DefaultArgParser.py
  tests/bears/BearTest.py
Labels: size/M, status/ci-approved

#5666 Profile_Bears: Add Profiling Interface doc
  docs/Developers/Profile_Bears.rst
  docs/index.rst
Labels: difficulty/medium, importance/low, process/pending review, size/XS, type/feature

#5691 .coafile: Change in pycodestyle_ignore list
  .coafile
Labels: difficulty/newcomer, importance/medium, size/XS

#5687 coala_main.py: Change variable name and value
  coalib/coala_main.py
Labels: difficulty/medium, difficulty/newcomer, importance/low, process/needs rebase, size/XS, type/bug, type/feature

#5693 XML.py: Add language definition for XML
  coalib/bearlib/languages/__init__.py
  coalib/bearlib/languages/definitions/XML.py
  tests/TestUtilities.py
Labels: area/aspects, area/documentation, area/languages, size/XS

#5700 Diff.py: Modify docstring of split_diff function
  coalib/results/Diff.py
Labels: area/documentation, difficulty/newcomer, size/XS

#5698 Sync templates
  .misc/appveyor.yml
  setup.cfg
  test-requirements.txt
Labels: process/pending review, size/XS

#5680 setup.cfg: Allow non-coverage of sys.exit(main())
  coalib/coala.py
  coalib/coala_ci.py
  coalib/coala_delete_orig.py
  coalib/coala_format.py
  coalib/coala_json.py
  setup.cfg
Labels: size/XS

#5475 Formatting: Add tastes to `FileLength` aspect
  coalib/bearlib/aspects/Formatting.py
Labels: area/aspects, area/documentation, size/XS

#5701 deprecate_settings: Support splitting setting
  coalib/bearlib/__init__.py
  tests/bearlib/DeprecateSettingsTest.py
Labels: size/XS, type/feature

#5696 CliParsing.py,ConfParser.py : Change in variable name
  coalib/parsing/CliParsing.py
  coalib/parsing/ConfParser.py
  tests/parsing/ConfParserTest.py
Labels: area/documentation, difficulty/low, importance/low, size/XS

#5504 language: Add `string_delimiter_escape` to language definitions
  coalib/bearlib/languages/definitions/C.py
  coalib/bearlib/languages/definitions/CPP.py
  coalib/bearlib/languages/definitions/CSS.py
  coalib/bearlib/languages/definitions/CSharp.py
  coalib/bearlib/languages/definitions/Fortran.py
  coalib/bearlib/languages/definitions/Golang.py
  coalib/bearlib/languages/definitions/Java.py
  coalib/bearlib/languages/definitions/JavaScript.py
  coalib/bearlib/languages/definitions/Python.py
  coalib/bearlib/languages/definitions/Tcl.py
  coalib/bearlib/languages/definitions/VisualBasic.py
  coalib/bearlib/languages/definitions/__init__.py
Labels: area/aspects, area/documentation, size/XS

#5324 PersistentHash: Preserve Order
  coalib/core/PersistentHash.py
  tests/core/PersistentHashTest.py
Labels: area/core, difficulty/low, size/XS

#5703 appveyor.yml: Install test requirements first
  .misc/appveyor.yml
  .misc/run_with_env.cmd
Labels: size/XS

#5709 Processing.py: Fix file dict logging
  coalib/processes/Processing.py
Labels: importance/medium, process/pending review, size/XS, type/bug

#3866 Included terminal command to install Git via XCode on MacOS
  docs/Developers/Git_Basics.rst
Labels: difficulty/newcomer, process/approved, size/XS, status/stale

#5721 Sync templates
  .gitignore
  setup.cfg
  setup.py
  test-requirements.txt
Labels: process/pending review, size/XS

#5733 JSON.py: Add language definition for JSON
  coalib/bearlib/languages/__init__.py
  coalib/bearlib/languages/definitions/JSON.py
  tests/TestUtilities.py
Labels: area/aspects, area/documentation, process/pending review, size/XS

#5728 JavaScript.py: Add alias 'node' to language JavaScript
  coalib/bearlib/languages/definitions/JavaScript.py
Labels: process/pending review, size/XS

#5707 FilterHelper.py: Rewrite filters
  coalib/coala.py
  coalib/parsing/FilterHelper.py
  coalib/results/result_actions/GeneratePatchesAction.py
  tests/parsing/FilterHelperTest.py
Labels: difficulty/low, importance/high, size/XS

#5585 core/__init__.py: Add module docstrings
  coalib/core/__init__.py
Labels: area/core, area/documentation, process/pending review, size/XS
