Repository coala/coala, pull requests merged in 2019-01, with the labels that each got.

#5937 setup.cfg: Raise AppVeyor timeout
  setup.cfg
Labels: area/CI, size/XS

#5960 Formatting.py: Fix typo
  coalib/bearlib/aspects/Formatting.py
Labels: area/aspects, area/documentation, process/pending review, size/XS

#5951 .coafile: Fix docstring typo builting --> builtin
  .coafile
Labels: area/documentation, difficulty/newcomer, process/pending review, size/XS

#5935 Setting.py: Fix docstring typo
  coalib/settings/Setting.py
Labels: area/documentation, difficulty/newcomer, size/XS

#5934 Writing_Good_Commits.rst: Fix grammar
  docs/Developers/Writing_Good_Commits.rst
Labels: size/XS
