Repository coala/coala, pull requests merged in 2019-02, with the labels that each got.

#5941 Review.rst: Add a note to the reviewers
  docs/Developers/Review.rst
Labels: area/CI, area/aspects, area/documentation, difficulty/low, difficulty/newcomer, process/pending review, size/XS

#5929 Newcomers_Guide.rst: Fix docstring typo
  docs/Developers/Newcomers_Guide.rst
Labels: area/documentation, difficulty/newcomer, process/pending review, size/XS

#5956 Globbing.py: Fix docstring typo
  coalib/parsing/Globbing.py
Labels: area/aspects, area/documentation, process/pending review, size/XS

#5897 Setting.py: Add end line number of setting
  coalib/settings/Section.py
  coalib/settings/Setting.py
  tests/parsing/ConfParserTest.py
  tests/settings/SettingTest.py
Labels: process/pending review, size/XS
